import { Injectable } from '@angular/core';
import { Shortlet } from '../../model/shortlet.model';

@Injectable({
  providedIn: 'root'
})
export class ShortletService {
  private shortlets: Shortlet[] = [
   {
    id: 'IP56729',
    image: '../../assets/img/gallery/10.jpg',
    title: 'Luxury 3 Bedroom Maisonette with BQ',
    description: 'Stylish 2-Bedroom Apartment / Flat Apartment for shortlet',
    location: 'Lekki phase 1',
    beds: 3,
    baths: 2,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '200,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-06-2025'
  },
  {
    id: 'IP56730',
    image: '../../assets/img/img-slide/21.jpg',
    title: 'Luxurious 4-Bedroom Waterfront Duplex',
    description: 'Luxurious 4-Bedroom Waterfront Duplex with premium finishing',
    location: 'Lekki phase 1',
    beds: 3,
    baths: 2,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Sale',
    price: '270,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '12-07-2025'
  },
  {
    id: 'IP56731',
    image: '../../assets/img/img-slide/32.jpg',
    title: 'Luxurious 2 Bedroom Apartment with Free Wi-Fi',
    description: 'Luxurious 2 Bedroom Apartment with free Wi-Fi for shortlet',
    location: 'Ikate, Lekki, Lagos.',
    beds: 3,
    baths: 2,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '270,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '04-08-2025'
  },
  {
    id: 'IP56732',
    image: '../../assets/img/service/21.jpg',
    title: '2 Bedroom Apartment With Bq',
    description: 'Modern 2 Bedroom Apartment with BQ and ample parking',
    location: 'Lekki Phase 1, Lagos',
    beds: 3,
    baths: 2,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '270,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '16-09-2025'
  },
  {
    id: 'IP56733',
    image: '../../assets/img/service/31.jpg',
    title: 'Newly Built 2 Bedroom Flat',
    description: 'Newly built 2 bedroom flat with modern finishes',
    location: 'Banana Island, Lagos',
    beds: 3,
    baths: 2,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Sale',
    price: '190,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '28-10-2025'
  },
  {
    id: 'IP56734',
    image: '../../assets/img/others/8.png',
    title: 'Decent Room And Parlour Self Con',
    description: 'Decent room and parlour self-contained apartment for shortlet',
    location: 'Ikeja, Lagos',
    beds: 2,
    baths: 2,
    type: 'Self Con',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '150,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '05-11-2025'
  },
  {
    id: 'IP56735',
    image: '../../assets/img/product/3.png',
    title: 'Luxury One Bedroom Mini Flat',
    description: 'Luxury one bedroom mini flat perfect for short stay',
    location: 'Lekki Phase 1, Lagos',
    beds: 3,
    baths: 2,
    type: 'Flat',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '270,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '14-12-2025'
  },
  {
    id: 'IP56736',
    image: '../../assets/img/product-3/2.jpg',
    title: 'Newly Built 1 Bedroom Flat',
    description: 'Newly built 1 bedroom flat for modern living',
    location: 'Ikate, Lagos',
    beds: 3,
    baths: 2,
    type: 'Flat',
    badges: ['Short Stay'],
    badge: 'For Sale',
    price: '100,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '22-01-2025'
  },
  {
    id: 'IP56737',
    image: '../../assets/img/product-3/3.jpg',
    title: 'Newly Built 3 Bedroom Apartment',
    description: 'Modern 3 bedroom apartment for family short stays',
    location: 'Ikoyi, Lagos',
    beds: 3,
    baths: 2,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '130,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '15-02-2025'
  },
 {
    id: 'IP56738',
    image: '../../assets/img/gallery/10.jpg',
    title: 'Modern 3-Bedroom Penthouse with Ocean View',
    description: 'Modern 3-Bedroom Penthouse with stunning ocean views for shortlet',
    location: 'Ikoyi, Lagos',
    beds: 3,
    baths: 3,
    type: 'Penthouse',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '550,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '10-03-2025'
},
{
    id: 'IP56739',
    image: '../../assets/img/img-slide/21.jpg',
    title: 'Executive 4-Bedroom Duplex with Pool',
    description: 'Executive 4-bedroom duplex with private pool and lounge area',
    location: 'Lekki Phase 2, Lagos',
    beds: 4,
    baths: 4,
    type: 'Duplex',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '400,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '20-03-2025'
},
{
    id: 'IP56740',
    image: '../../assets/img/img-slide/32.jpg',
    title: 'Luxury 2-Bedroom Apartment in Admiralty Way',
    description: 'Luxury 2-bedroom apartment along Admiralty Way for shortlet',
    location: 'Lekki Phase 1, Lagos',
    beds: 2,
    baths: 2,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '250,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '01-04-2025'
},
{
    id: 'IP56741',
    image: '../../assets/img/service/21.jpg',
    title: 'Spacious Studio Apartment with Balcony',
    description: 'Spacious studio apartment with private balcony and city view',
    location: 'Ikate, Lekki, Lagos',
    beds: 1,
    baths: 1,
    type: 'Studio',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '120,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '10-04-2025'
},
{
    id: 'IP56742',
    image: '../../assets/img/service/31.jpg',
    title: 'Furnished 1-Bedroom Flat with Wi-Fi',
    description: 'Fully furnished 1-bedroom flat with high-speed Wi-Fi',
    location: 'Victoria Island, Lagos',
    beds: 1,
    baths: 1,
    type: 'Flat',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '150,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '22-04-2025'
},
{
    id: 'IP56743',
    image: '../../assets/img/others/8.png',
    title: 'Elegant 2-Bedroom Maisonette',
    description: 'Elegant 2-bedroom maisonette with modern fittings',
    location: 'Oniru, Lagos',
    beds: 2,
    baths: 2,
    type: 'Maisonette',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '300,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '01-05-2025'
},
{
    id: 'IP56744',
    image: '../../assets/img/product/3.png',
    title: 'Cozy Mini Flat for Short Stay',
    description: 'Cozy and affordable mini flat for short stays',
    location: 'Ikoyi, Lagos',
    beds: 1,
    baths: 1,
    type: 'Mini Flat',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '100,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '14-05-2025'
},
{
    id: 'IP56745',
    image: '../../assets/img/product-3/2.jpg',
    title: 'Newly Built 4 Bedroom Terrace',
    description: 'Newly built 4-bedroom terrace with spacious living area',
    location: 'Lekki Phase 1, Lagos',
    beds: 4,
    baths: 4,
    type: 'Terrace',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '350,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '20-05-2025'
},
{
    id: 'IP56746',
    image: '../../assets/img/product-3/3.jpg',
    title: 'Classic 2 Bedroom Apartment with Gym Access',
    description: 'Classic 2-bedroom apartment with free gym membership',
    location: 'Ikate, Lagos',
    beds: 2,
    baths: 2,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '220,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '03-06-2025'
},
{
    id: 'IP56747',
    image: '../../assets/img/gallery/10.jpg',
    title: 'Waterfront 5-Bedroom Luxury Villa',
    description: 'Magnificent 5-bedroom villa with waterfront views and private dock',
    location: 'Banana Island, Lagos',
    beds: 5,
    baths: 5,
    type: 'Villa',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '950,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '15-06-2025'
},
{
    id: 'IP56748',
    image: '../../assets/img/img-slide/21.jpg',
    title: 'Contemporary 1 Bedroom Loft',
    description: 'Contemporary 1-bedroom loft with modern design',
    location: 'Victoria Island, Lagos',
    beds: 1,
    baths: 1,
    type: 'Loft',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '180,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '22-06-2025'
},
{
    id: 'IP56749',
    image: '../../assets/img/img-slide/32.jpg',
    title: 'Premium 3 Bedroom Apartment with Maid Room',
    description: 'Premium 3-bedroom apartment with dedicated maid room',
    location: 'Ikoyi, Lagos',
    beds: 3,
    baths: 3,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '350,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '01-07-2025'
},
{
    id: 'IP56750',
    image: '../../assets/img/service/21.jpg',
    title: 'Affordable Studio Apartment in Lekki',
    description: 'Affordable and modern studio apartment with security',
    location: 'Lekki Phase 1, Lagos',
    beds: 1,
    baths: 1,
    type: 'Studio',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '90,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '11-07-2025'
},
{
    id: 'IP56751',
    image: '../../assets/img/service/31.jpg',
    title: 'Highrise 2 Bedroom Penthouse with Sea View',
    description: 'Highrise 2-bedroom penthouse with breathtaking sea view',
    location: 'Oniru, Lagos',
    beds: 2,
    baths: 2,
    type: 'Penthouse',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '420,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '20-07-2025'
},
{
    id: 'IP56752',
    image: '../../assets/img/others/8.png',
    title: 'Modern 3 Bedroom Apartment with Swimming Pool',
    description: 'Modern 3-bedroom apartment with private swimming pool',
    location: 'Ikate, Lekki',
    beds: 3,
    baths: 3,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '310,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '28-07-2025'
},
{
    id: 'IP56753',
    image: '../../assets/img/product/3.png',
    title: 'Furnished Room and Parlour Self-Contained',
    description: 'Furnished room and parlour self-contained apartment for rent',
    location: 'Lekki Phase 2, Lagos',
    beds: 1,
    baths: 1,
    type: 'Self Con',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '110,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '06-08-2025'
},
{
    id: 'IP56754',
    image: '../../assets/img/product-3/2.jpg',
    title: '4 Bedroom Semi Detached Duplex',
    description: 'Spacious 4-bedroom semi detached duplex with modern design',
    location: 'Banana Island, Lagos',
    beds: 4,
    baths: 4,
    type: 'Duplex',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '500,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '15-08-2025'
},
{
    id: 'IP56755',
    image: '../../assets/img/product-3/3.jpg',
    title: 'Luxury 2 Bedroom Apartment with Modern Kitchen',
    description: 'Luxury 2-bedroom apartment with modern fitted kitchen',
    location: 'Victoria Island, Lagos',
    beds: 2,
    baths: 2,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '250,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '23-08-2025'
},
{
    id: 'IP56756',
    image: '../../assets/img/gallery/10.jpg',
    title: 'Serviced 1 Bedroom Apartment in Ikoyi',
    description: 'Serviced 1-bedroom apartment with 24/7 power and security',
    location: 'Ikoyi, Lagos',
    beds: 1,
    baths: 1,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '190,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '30-08-2025'
},
{
    id: 'IP56757',
    image: '../../assets/img/img-slide/21.jpg',
    title: 'Decent 2 Bedroom Apartment in Oniru',
    description: 'Decent 2-bedroom apartment with ample parking space',
    location: 'Oniru, Lagos',
    beds: 2,
    baths: 2,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '210,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '05-09-2025'
},
{
    id: 'IP56758',
    image: '../../assets/img/img-slide/32.jpg',
    title: 'Bright 3 Bedroom Bungalow with Parking',
    description: 'Bright 3-bedroom bungalow with spacious compound and parking',
    location: 'Lekki Phase 2, Lagos',
    beds: 3,
    baths: 3,
    type: 'Bungalow',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '260,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '12-09-2025'
},
{
    id: 'IP56759',
    image: '../../assets/img/service/21.jpg',
    title: 'Modern Studio Apartment with Rooftop Access',
    description: 'Modern studio apartment with private rooftop lounge',
    location: 'Victoria Island, Lagos',
    beds: 1,
    baths: 1,
    type: 'Studio',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '130,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '20-09-2025'
},
{
    id: 'IP56760',
    image: '../../assets/img/service/31.jpg',
    title: 'Spacious 2 Bedroom Flat with Parking Space',
    description: 'Spacious 2-bedroom flat with secured parking area',
    location: 'Ikate, Lekki',
    beds: 2,
    baths: 2,
    type: 'Flat',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '200,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '29-09-2025'
},
{
    id: 'IP56761',
    image: '../../assets/img/others/8.png',
    title: 'Affordable 1 Bedroom Self-Contained',
    description: 'Affordable 1-bedroom self-contained with all utilities',
    location: 'Lekki Phase 1, Lagos',
    beds: 1,
    baths: 1,
    type: 'Self Con',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '80,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '05-10-2025'
},
{
    id: 'IP56762',
    image: '../../assets/img/product/3.png',
    title: '5 Bedroom Fully Detached Mansion',
    description: 'Luxury 5-bedroom fully detached mansion with pool',
    location: 'Banana Island, Lagos',
    beds: 5,
    baths: 5,
    type: 'Mansion',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '1,200,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '13-10-2025'
},
{
    id: 'IP56763',
    image: '../../assets/img/product-3/2.jpg',
    title: 'Luxury 3 Bedroom Apartment with Ocean Breeze',
    description: 'Luxury 3-bedroom apartment with fresh ocean breeze',
    location: 'Oniru, Lagos',
    beds: 3,
    baths: 3,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '380,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '20-10-2025'
},
{
    id: 'IP56764',
    image: '../../assets/img/product-3/3.jpg',
    title: 'Brand New 2 Bedroom Flat in Victoria Island',
    description: 'Brand new 2-bedroom flat in the heart of Victoria Island',
    location: 'Victoria Island, Lagos',
    beds: 2,
    baths: 2,
    type: 'Flat',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '220,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '28-10-2025'
},
{
    id: 'IP56765',
    image: '../../assets/img/gallery/10.jpg',
    title: '1 Bedroom Apartment with Private Balcony',
    description: '1-bedroom apartment with private balcony and city views',
    location: 'Ikoyi, Lagos',
    beds: 1,
    baths: 1,
    type: 'Apartment',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '160,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '05-11-2025'
},
{
    id: 'IP56766',
    image: '../../assets/img/img-slide/21.jpg',
    title: 'Elegant Studio Apartment in Lekki Phase 1',
    description: 'Elegant studio apartment perfect for singles and couples',
    location: 'Lekki Phase 1, Lagos',
    beds: 1,
    baths: 1,
    type: 'Studio',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '100,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Admin',
    listedDate: '12-11-2025'
},
{
    id: 'IP56767',
    image: '../../assets/img/img-slide/32.jpg',
    title: 'Cozy 2 Bedroom Flat with Gated Security',
    description: 'Cozy 2-bedroom flat with gated security and parking',
    location: 'Ikate, Lagos',
    beds: 2,
    baths: 2,
    type: 'Flat',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '200,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Owner',
    listedDate: '18-11-2025'
},
{
    id: 'IP56768',
    image: '../../assets/img/service/21.jpg',
    title: 'Spacious 4 Bedroom Duplex in Banana Island',
    description: 'Spacious 4-bedroom duplex with modern finishes in Banana Island',
    location: 'Banana Island, Lagos',
    beds: 4,
    baths: 4,
    type: 'Duplex',
    badges: ['Short Stay'],
    badge: 'For Rent',
    price: '600,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-11-2025'
}


  ];

   getShortlets(): Shortlet[] {
    return this.shortlets;
  }

  filterShortlets(criteria: any): Shortlet[] {
    return this.shortlets.filter(s => {
      const priceValue = parseInt(s.price.replace(/[^\d]/g, ''), 10);

      return (!criteria.location || s.location.toLowerCase().includes(criteria.location.toLowerCase())) &&
             (!criteria.purpose || s.badge.toLowerCase() === criteria.purpose.toLowerCase()) &&
             (!criteria.type || s.type.toLowerCase() === criteria.type.toLowerCase()) &&
             (!criteria.beds || s.beds === +criteria.beds) &&
             (!criteria.minPrice || priceValue >= +criteria.minPrice) &&
             (!criteria.maxPrice || priceValue <= +criteria.maxPrice);
    });
  }

}
