import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-all-shortlets-single',
  templateUrl: './all-shortlets-single.component.html',
  styleUrls: ['./all-shortlets-single.component.scss']
})
export class AllShortletsSingleComponent implements OnInit {
shortStayListings = [
  // {
  //   image: '../../../assets/img/gallery/10.jpg',
  //   type: 'Apartment',
  //   price: '₦170,000',
  //   frequency: '/Day',
  //   title: 'Stylish 2-Bedroom Apartment',
  //   description: 'Stylish 2-Bedroom Apartment / Flat Apartment for shortlet',
  //   beds: 3,
  //   baths: 2,
  //   location: 'Lekki phase 1, Lagos',
  //   badge: 'Short Stay',
  //   agentImage: '../../../assets/img/blog/author.jpg',
  //   agentName: 'William Seklo',
  //   agentTitle: 'Realtor',
  //   listedDate: '25-06-2025'
  // },
    {
    id: '678564',
    image: '../../assets/img/gallery/10.jpg',
    title: 'Stylish 2-Bedroom Apartment',
    description: 'Stylish 2-Bedroom Apartment / Flat Apartment for shortlet',
    location: 'Lekki phase 1',
    beds: 3,
    baths: 2,
    type: '2 Bedroom',
    badge: 'Short Stay',
    price: '₦200,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-06-2025'
  },
  {
    image: '../../assets/img/img-slide/21.jpg',
    title: 'Luxurious 4-Bedroom Waterfront Duplex',
     description: 'Luxurious 4-Bedroom Waterfront Duplex / Duplex for shortlet',
    location: 'Lekki phase 1',
    beds: 3,
    baths: 2,
    type: '4 Bedroom',
    badges: ['Short Stay'],
    badge: 'Short Stay',
    price: '₦270,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-06-2025'
  },
  {
    image: '../../assets/img/img-slide/32.jpg',
    title: 'Luxurious 2 Bedroom Apartment with Free Wi-Fi',
    description: 'Luxurious 2 Bedroom Apartment with Free Wi-Fi / 2 Bedroom Apartment for shortlet',
    location: 'Ikate, Lekki, Lagos.',
    beds: 3,
    baths: 2,
    type: '2 Bedroom',
    badges: ['Apartment'],
    badge: 'Short Stay',
    price: '₦270,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-06-2025'
  },
  {
    image: '../../assets/img/service/21.jpg',
    title: '2 Bedroom Apartment With Bq',
    description: '2 Bedroom Apartment With Bq / Apartment for shortlet',
    location: 'Lekki Phase 1, Lagos',
    beds: 3,
    baths: 2,
    type: '2 Bedroom',
    badges: ['Apartment'],
    badge: 'Short Stay',
    price: '₦270,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-06-2025'
  },
  {
    image: '../../assets/img/service/31.jpg',
    title: 'Newly Built 2 Bedroom Flat',
    description: 'Newly Built 2 Bedroom Flat / Flat for shortlet',
    location: 'Banana Island, Lagos',
    beds: 3,
    baths: 2,
    type: '2 Bedroom',
    badges: ['Apartment'],
    badge: 'Short Stay',
    price: '₦190,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-06-2025'
  },
  {
    image: '../../assets/img/others/8.png',
    title: 'Decent Room And Parlour Self Con',
    description: 'Decent Room And Parlour Self Con / Self Con for shortlet',
    location: 'Ikeja, Lagos',
    beds: 3,
    baths: 2,
    type: 'Room And Parlour',
    badges: ['Apartment'],
    badge: 'Short Stay',
    price: '₦150,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-06-2025'
  },
  {
    image: '../../assets/img/product/3.png',
    title: 'Luxury One Bedroom Mini Flat',
    description: 'Luxury One Bedroom Mini Flat / One Bedroom Apartment for shortlet',
    location: 'Lekki Phase 1, Lagos',
    beds: 3,
    baths: 2,
    type: 'Flat',
    badges: ['Apartment'],
    badge: 'Short Stay',
    price: '₦270,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-06-2025'
  },
  {
    image: '../../assets/img/product-3/2.jpg',
    title: 'Newly Built 1 Bedroom Flat',
    description: 'Newly Built 1 Bedroom Flat / 1 Bedroom Flat Apartment for shortlet',
    location: 'Ikate, Lagos',
    beds: 3,
    baths: 2,
    type: '1 Bedroom',
    badges: ['Apartment'],
    badge: 'Short Stay',
    price: '₦100,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-06-2025'
  },
  {
    image: '../../assets/img/product-3/3.jpg',
    title: 'Newly Built 3 Bedroom Apartment',
    description: 'Newly Built 3 Bedroom Apartment / 3 Bedroom Flat Apartment for shortlet',
    location: 'Ikoyi, Lagos',
    beds: 3,
    baths: 2,
    type: '3 Bedroom',
    badges: ['Apartment'],
    badge: 'Short Stay',
    price: '₦130,000',
    frequency: '/Day',
    agentImage: '../../../assets/img/blog/author.jpg',
    agentName: 'William Seklo',
    agentTitle: 'Realtor',
    listedDate: '25-06-2025'
  }
];

  constructor() { }

  ngOnInit(): void {
  }

}
